### ISSUE TITLE
AssertionError when assigning a function to multiple identifiers.

### ISSUE THREAD

**Issue by beickhoff** [cliffclick/aa#17]
For example:

```
test("f = g = {-> 3}; f() == g();", TypeInt.TRUE);
```
```
java.lang.AssertionError
	at com.cliffc.aa.node.FunPtrNode.bind(FunPtrNode.java:89)
	at com.cliffc.aa.Parse.stmt(Parse.java:336)
	…
```

In FunPtrNode#bind, `_name` is already set to "f", but `tok` is now "g".

**Comment by cliffclick** [comment]
Nice!  Too strong assert.  Fixed in branch "merging_with_hm" sha 65d7aa4f.
